[package]
name = "agent"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
libp2p.workspace = true
futures.workspace = true
serde.workspace = true
toml.workspace = true
ciborium.workspace = true
ed25519-dalek.workspace = true
multibase.workspace = true
uuid.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sysinfo = "0.30"
dirs = "5.0"
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
serde_json.workspace = true
